spring:
  application:
    name:unitasks

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:unitasks;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

server:
  port: 8080